Added color palette result page
MrSpaceMan1/SkinResque pull request #100
Opened 2022-12-28 22:17 UTC by dpionk

2023-01-03 11:36 UTC, MrSpaceMan1 approved these changes

2023-01-03 11:48 UTC, kbojarowska requested changes
<img width="960" alt="image" src="https://user-images.githubusercontent.com/83237280/210351161-e22e33aa-e25a-4848-af0c-f39a6fe618e2.png">
Please use % and rem values, everything is to big because of using fixed px
<img width="541" alt="image" src="https://user-images.githubusercontent.com/83237280/210351264-f9ee1f9d-8fa0-4896-945d-b239a9d24045.png">
Add gap between colors

There is no save button
And what for where the arrows? They are not doing anything right now (I know that they were in figma, but what for)

2023-01-03 11:48 UTC, kbojarowska commented on skin-resque-frontend/src/pages/FrontPage/FrontPage.js
> +					<Button><Link to='/color-test/try'>Color Test</Link></Button>
Why do you changed this? This button should link to info not test

2023-01-03 12:07 UTC, dpionk commented
so for what should I include the save button? Because it wont do anything.

2023-01-03 12:15 UTC, kbojarowska commented
> so for what should I include the save button? Because it wont do anything.

mock it, everything we do now would make future work faster, we wouldn't have to look for every page to search for missing elements, but just adding new features

2023-01-03 12:16 UTC, dpionk commented
Then I don't understand why adding arrows is a problem

2023-01-14 10:59 UTC, kbojarowska approved these changes

2023-01-14 12:44 UTC, merged