Fixed questions page
MrSpaceMan1/SkinResque pull request #101
Opened 2022-12-28 22:36 UTC by dpionk

checkboxes do not stay checked, this will be fixed when test is completedand we will have some answers

2023-01-03 11:35 UTC, MrSpaceMan1 commented on skin-resque-frontend/src/pages/SkintypeTest/Questions/Questions.js
> +							{answersToDisplay && answersToDisplay}
Why the double the `answersToDisplay`?

2023-01-03 11:51 UTC, kbojarowska requested changes
<img width="958" alt="image" src="https://user-images.githubusercontent.com/83237280/210351900-ff08312e-6569-4307-9630-efc0acd043c3.png">
Everything is too big, not using svg background

2023-01-03 11:56 UTC, dpionk commented
@kbojarowska  because the fix was not including using svg background. It was about question number and checkboxes.

2023-01-03 12:16 UTC, kbojarowska commented
> @kbojarowska because the fix was not including using svg background. It was about question number and checkboxes.

we were talking about changing all of the skintype test backgrounds to svg

2023-01-03 12:17 UTC, dpionk commented
Then I would include this change with different issue

2023-01-03 12:18 UTC, dpionk commented
This was corresponding with issue where there were two things to fix and they were not about svg background

2023-01-08 15:01 UTC, dpionk commented
I deleted pagination as it was using links which are not compatible. I will be working on skin type test right now.

2023-01-08 17:10 UTC, MrSpaceMan1 approved these changes

2023-01-14 10:58 UTC, kbojarowska approved these changes

2023-01-14 12:37 UTC, merged