Create skin type test info page
MrSpaceMan1/SkinResque pull request #58
Opened 2022-11-15 18:16 UTC by dpionk

Created skin type test info page along with routes

2022-11-20 11:57 UTC, kbojarowska requested changes
Why do you want to seperate one page info two parts? Idk if we need it

2022-11-20 11:57 UTC, kbojarowska commented on skin-resque-frontend/src/pages/SkintypeTest/Info/Info.js
> +			<div className='info'>
This part should be justified

2022-11-20 11:57 UTC, kbojarowska commented on skin-resque-frontend/src/pages/SkintypeTest/SkintypeTestPage/SkintypeTestPage.js
> +				<Heading size='large'>Skintype Test</Heading>
test should be lower

2022-11-20 17:11 UTC, MrSpaceMan1 approved these changes

2022-11-20 17:25 UTC, dpionk commented
> Why do you want to seperate one page info two parts? Idk if we need it

Because I already implemented  questions page which will be rendering on SkinTypeTestPage component. I needed to merge these changes in order to add the questions part next

2022-11-20 18:04 UTC, dpionk commented
@kbojarowska  I updated the code

2022-11-21 19:28 UTC, kbojarowska approved these changes

2022-11-26 13:59 UTC, merged