Created checkbox component
MrSpaceMan1/SkinResque pull request #59
Opened 2022-11-15 20:59 UTC by dpionk

2022-11-20 12:02 UTC, kbojarowska requested changes
Checkbox is too big, the check icon is too small
"checked" props doesn't work

2022-11-20 13:06 UTC, kbojarowska commented
If it's possible please use fi icons from react icons gallery

2022-11-20 17:19 UTC, MrSpaceMan1 requested changes

2022-11-20 17:19 UTC, MrSpaceMan1 commented on skin-resque-frontend/src/components/Checkbox/Checkbox.js
> +	const [isChecked, setIsChecked] = useState(checked);
isChecked not used

2022-11-20 17:19 UTC, MrSpaceMan1 commented on skin-resque-frontend/src/components/Checkbox/Checkbox.js
> +			<input type='checkbox' onChange={() => setIsChecked((checked) => !checked)}/>
Input doesn't use isChecked for its checked property

2022-11-20 17:19 UTC, MrSpaceMan1 commented on skin-resque-frontend/src/components/Checkbox/Checkbox.js
> +};
Lack of children type

2022-11-26 14:39 UTC, dpionk commented
@kbojarowska  @MrSpaceMan1  I made changes after review, I tried using react icons but it was hard for me as I could not find on internet how to do it and had no idea

2022-12-01 11:41 UTC, MrSpaceMan1 approved these changes

2022-12-09 08:33 UTC, kbojarowska approved these changes

2022-12-09 08:33 UTC, merged