Added login and register page
MrSpaceMan1/SkinResque pull request #94
Opened 2022-12-22 17:07 UTC by dpionk

2022-12-26 16:06 UTC, kbojarowska requested changes

2022-12-26 16:06 UTC, kbojarowska commented on skin-resque-frontend/src/pages/LoginRegister/LoginRegister.scss
> +		gap: 30px;
replace px with rems

2022-12-26 16:06 UTC, kbojarowska commented on skin-resque-frontend/src/pages/LoginRegister/LoginRegister.js
> +							{!isLogin && <div className='field'>
the username - password - email order looks weird for me, and in figma we had double password field in register

2022-12-26 16:06 UTC, kbojarowska commented on skin-resque-frontend/src/pages/LoginRegister/LoginRegister.scss
> +		width: 50%;
I think that this element is too narrow

2022-12-26 16:06 UTC, kbojarowska commented on skin-resque-frontend/src/pages/LoginRegister/LoginRegister.js
> +						<Heading size='small'>{isLogin ? "Don't" : 'Already'} have an account? <Link to={isLogin ? '/register' : '/login'}>{isLogin ? 'Sign up' : 'Log in'} here</Link></Heading>
I think that it will look good if sing up here / log in here would underline on hover

2022-12-26 16:06 UTC, kbojarowska commented on skin-resque-frontend/src/pages/LoginRegister/LoginRegister.js
> +								<Field type='password' name='password' />
make the fields all the same length
how it looks rn:
![image](https://user-images.githubusercontent.com/83237280/209566177-24ccd1fa-d7a7-4519-be09-47b1e4ae4b20.png)

how it should look:
![image](https://user-images.githubusercontent.com/83237280/209566191-b8fa959d-56e9-426d-8a01-d5d430c5f69d.png)

2022-12-28 21:46 UTC, dpionk commented
@kbojarowska I addressed your change requests and updated this component

2023-01-03 11:29 UTC, MrSpaceMan1 approved these changes

2023-01-03 11:55 UTC, kbojarowska approved these changes

2023-01-03 11:55 UTC, kbojarowska commented
resolve conflicts, everything looks good :)

2023-01-03 11:59 UTC, merged